---
title: "Gov 50 Final Project"
author: "Conner Huey"
description: "My Final Project"
output:
  distill::distill_article:
    self_contained: false
---

## Data Visualization

```{r}
library(tidyverse)

civilwar |>
  filter(gdpenl > 0) |>
  ggplot(aes(x = gdpenl, y = polity2)) +
  geom_point(size = 0.5) +
  geom_smooth() +
  ylim(-10, 10)
```


## Project Proposal

The research question for my final project is "what are the effects of democratization on a country's likelihood of civil war?" I hypothesize that the higher the absolute value of a country's polity score (index of democratization) in a given year, the less likely that a country is to experience a civil war in the same year. My hypothesis is rooted in the literature of comparative politics and political theory, of which there exist multiple schools of thought are outlined which attempt to explain the relationship between regime type and its effects on civil war. For instance, according to a 2017 publication in the Brookings Institution, Piccone argues that democracies are less likely to experience civil wars than hybrid regimes because of the presence of strong institutions that allow possible rebels to resolve political disagreements peacefully (Piccone, 2017). Similarly in scope, Slater and Fenner approach this question from a different angle, contending that strong regimes are associated with strong states to prop up the regime, meaning political stability (Slater and Fenner, 2011). The common thread tying this literature together is that the stronger a regime, the more stable a country which likely leads to less civil wars.

My explanatory variable of interest is the polity score of a country, which is coded as "polity2" and measures the index of democratization in a country. The polity score of a country is coded on a scale from -10 (least democratic/most authoritarian) to 10 (most democratic/least authoritarian). My outcome variable of interest is the presence of a civil war in a country, which is coded as "war" and notes whether or not a country is currently experiencing a civil war. "War" is coded as either 0 (no civil war in that country) or 1 (there is a civil war in that country). If my hypothesis is correct, we should expect to see a greater proportion of countries with a higher absolute value of polity scores being associated with no civil wars in their countries compared to there existing civil wars in their countries. Similarly, we should expect to see a greater proportion of countries with lower absolute value of polity scores being associated with the existence of civil wars in their countries compared to no civil wars. If my hypothesis is incorrect, we will not see a relationship between the polity score of a country and the presence of a civil war in that country.


## Project thoughts

For my final project, I'm interested in exploring topics broadly related to voter identity and political behavior from the 1990s to the present day. In particular, I'm interested in exploring either voter shift during the 1994 Congressional election, which coincides with Newt Gingrich's Contract with America, or the 2016 presidential election.